Rwa 844 - SearchForCompletable endpoint plugin
hmcts/wa-task-management-api pull request #411
Opened 2021-10-28 18:57 UTC by indvamshi

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-844

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-10-29 14:56 UTC, raghera submitted a review, later dismissed

2021-11-10 15:16 UTC, dharmendrak approved these changes

2021-11-10 17:14 UTC, alexbaeza commented on src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerCFTTest.java
> +        common.clearAllRoleAssignments(authenticationHeaders);
No need to clear all role assignments on the before each test will be using a single user and the roles are cleared as part of the setupOrganisationalRoleAssignment

2021-11-11 09:26 UTC, alexbaeza requested changes

2021-11-11 09:45 UTC, indvamshi commented on src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerCFTTest.java
> +        );
The above test is related to autoAssign so its ignored. I will delete the test as this tests are covered in another ticket.

2021-11-11 10:01 UTC, indvamshi commented on src/functionalTest/java/uk/gov/hmcts/reform/wataskmanagementapi/controllers/PostTaskForSearchCompletionControllerCFTTest.java
> +    }
yes, but without third argument, multiple FTs use the method so have to change in most FTs.

2021-11-11 10:04 UTC, indvamshi commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/cft/query/RoleAssignmentFilter.java
> +        LocalDateTime endTime = roleAssignment.getEndTime();
Its Provider-Consumer contract, they should tell us if they change to ZonedDateTime.

2021-11-11 10:43 UTC, alexbaeza approved these changes

2021-11-11 12:24 UTC, merged