feat:Update api to include role category (RWA-944)
hmcts/wa-task-management-api pull request #456
Opened 2021-12-01 15:02 UTC by dharmendrak

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-944

### Change description ###

Update api to include role category

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-12-06 10:47 UTC, serdaroguzhanakin submitted a review, later dismissed

2021-12-15 13:08 UTC, indvamshi submitted a review, later dismissed

2021-12-16 17:06 UTC, BenNzewi reviewed
This needs to be rebased with 957 so we can see the actual work done so far.

2021-12-16 17:08 UTC, BenNzewi requested changes
I cross referenced RWA-957 and the changes there for for including description on all our search task endpoints look incorrect. It should be mapped to the task and surfaceable without having to hard code.

The FTs will need reviewing

2021-12-17 13:36 UTC, BenNzewi commented on src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskBySearchForCompletablePactTest.java
> +            RoleCategory.LEGAL_OPERATIONS.name(),
can we also update the local consumer to include role_category? TaskManagementGetTasksBySearchForCompletableConsumerTest

2021-12-17 13:37 UTC, BenNzewi commented on src/contractTest/java/uk/gov/hmcts/reform/wataskmanagementapi/provider/TaskManagementGetTaskProviderTest.java
> +            RoleCategory.LEGAL_OPERATIONS.name(),
can we also update the local consumer to include role_category?

TaskManagerGetTaskConsumerTest

2021-12-17 13:51 UTC, BenNzewi reviewed
is there a ticket to update the post-deployment-ft scenarios with role category?

2021-12-21 15:14 UTC, BenNzewi approved these changes

2021-12-21 15:16 UTC, merged