Rwa 943
hmcts/wa-task-management-api pull request #467
Opened 2021-12-12 20:31 UTC by mkayad

### JIRA link (if applicable) ###
[RWA-943](https://tools.hmcts.net/jira/browse/RWA-943)

### Change description ###
https://tools.hmcts.net/jira/browse/RWA-943

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2021-12-15 18:09 UTC, dharmendrak approved these changes

2021-12-15 18:25 UTC, indvamshi requested changes
Can you add a FT with search parameter as caseId, so you can retrieve one record and verify the description matching the one in den

2021-12-16 15:48 UTC, dharmendrak approved these changes

2021-12-17 13:07 UTC, vgulapally commented
> Can you add a FT with search parameter as caseId, so you can retrieve one record and verify the description matching the one in den

Added FTs

2021-12-17 13:09 UTC, vgulapally commented
> Can you add a FT with search parameter as caseId, so you can retrieve one record and verify the description matching the one in den

2021-12-17 13:23 UTC, indvamshi approved these changes

2021-12-17 13:34 UTC, dharmendrak approved these changes

2021-12-20 18:23 UTC, merged