RWA-1595 claim task already assigned will throw 409
hmcts/wa-task-management-api pull request #666
Opened 2022-07-07 17:12 UTC by chrisdavecm

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-1595

### Change description ###
claim task already assigned will throw 409

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-07-08 11:35 UTC, rasikasri submitted a review, later dismissed

2022-07-08 11:35 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementService.java
> +                cftTaskDatabaseService.saveTask(task);
Do you need to save the task here? as you are throwing and exception, transaction will be rollback anyway. isn't it?

2022-07-08 11:55 UTC, dharmendrak approved these changes

2022-07-08 11:56 UTC, dharmendrak requested changes
please action what Rasikha suggested

2022-07-15 12:06 UTC, dharmendrak approved these changes

2022-08-04 13:53 UTC, merged