RWA-1663 task action attributes for warnings
hmcts/wa-task-management-api pull request #871
Opened 2022-12-02 10:03 UTC by vgulapally

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-1663

### Change description ###
task action attributes for warnings

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-14 15:34 UTC, rasikasri submitted a review, later dismissed

2022-12-16 16:12 UTC, rasikasri approved these changes

2022-12-22 09:29 UTC, rasikasri approved these changes

2022-12-28 13:05 UTC, BenNzewi requested changes
Is there an update for action when there are warnings? I could not find any updates to existing warning tests in FT to verify the change. For example PostTaskSearchController.should_return_a_200_with_search_results_and_warnings() or

2023-01-04 11:01 UTC, vgulapally commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/TaskManagementService.java
> +        if (taskAction != null) {
done

2023-01-04 13:21 UTC, vgulapally commented
> Is there an update for action when there are warnings? I could not find any updates to existing warning tests in FT to verify the change. For example PostTaskSearchController.should_return_a_200_with_search_results_and_warnings() or

Integration test don't exist for add notes, have created new test and added assertions

2023-01-18 09:52 UTC, serdaroguzhanakin approved these changes

2023-01-18 09:57 UTC, merged