Generalise date calculation
hmcts/wa-task-management-api pull request #891
Opened 2022-12-14 12:18 UTC by dharmendrak

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-2098

### Change description ###

Make date calculation generic

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-12-14 16:24 UTC, rasikasri approved these changes

2023-01-25 12:50 UTC, rasikasri requested changes

2023-01-25 12:50 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/domain/entities/calendar/NextHearingDateIntervalData.java
> +public class NextHearingDateIntervalData {
Why do you need a new class for next hearing date data and and due date data. You can use the DateTypeIntervalData class for all the types

2023-01-25 12:50 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateIntervalReCalculator.java
> +    private DateTypeIntervalData readDueDateOriginFields(List<ConfigurationDmnEvaluationResponse> dueDateProperties) {
This method is same as the readDueDateOriginFields in the super class other than checking the canReconfigure flag. You can pass it as a parameter to the method. Please see how its done in this pr https://github.com/hmcts/wa-task-management-api/pull/915

2023-01-25 12:50 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateCalculator.java
> +    ConfigurationDmnEvaluationResponse calculatedDate(
This method should be protected visibility and rest of the methods here are private

2023-01-25 12:50 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/DueDateTimeCalculator.java
> +    ConfigurationDmnEvaluationResponse calculatedDate(
Same here, protected scope

2023-01-25 12:50 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/NextHearingDateIntervalReCalculator.java
> +    private DateTypeIntervalData readOriginFields(List<ConfigurationDmnEvaluationResponse> dateTypeProperties) {
Same comment as of due date re-calculator, you can use the method in super class with canReconfigure parameter

2023-01-25 12:50 UTC, rasikasri commented on src/main/java/uk/gov/hmcts/reform/wataskmanagementapi/services/calendar/PriorityDateIntervalReCalculator.java
> +    private DateTypeIntervalData readPriorityDateOriginFields(
same here

2023-01-27 12:27 UTC, rasikasri submitted a review, later dismissed

2023-02-08 09:44 UTC, PrasadKumarP approved these changes

2023-02-08 09:44 UTC, merged